// =============================================================================
// Schema Toolkit - Documentation Generator
// =============================================================================

import {
  TableDef,
  ColumnDef,
  ForeignKeyDef,
  UserStory,
  ModuleDef,
} from './types';

/**
 * Generate comprehensive database documentation in Markdown
 */
export function generateDocumentation(
  tables: TableDef[],
  projectName: string = 'Database Schema',
  options: {
    includeTOC?: boolean;
    includeRelationships?: boolean;
    includeStatistics?: boolean;
    includeDDL?: boolean;
  } = {}
): string {
  const opts = {
    includeTOC: true,
    includeRelationships: true,
    includeStatistics: true,
    includeDDL: false,
    ...options,
  };

  const lines: string[] = [];
  const now = new Date().toISOString().split('T')[0];

  // Header
  lines.push(`# ${projectName} — Database Documentation`);
  lines.push('');
  lines.push(`> Auto-generated on ${now}`);
  lines.push(`> Generated by Schema Toolkit`);
  lines.push('');

  // Quick Stats
  if (opts.includeStatistics) {
    lines.push('## 📊 Quick Statistics');
    lines.push('');
    lines.push('| Metric | Count |');
    lines.push('|--------|-------|');
    lines.push(`| Total Tables | ${tables.length} |`);
    lines.push(`| Total Columns | ${tables.reduce((a, t) => a + t.columns.length, 0)} |`);
    lines.push(`| Total Relationships | ${tables.reduce((a, t) => a + t.foreignKeys.length, 0)} |`);
    lines.push(`| Primary Keys | ${tables.reduce((a, t) => a + t.columns.filter(c => c.isPrimaryKey).length, 0)} |`);
    lines.push(`| Nullable Columns | ${tables.reduce((a, t) => a + t.columns.filter(c => c.isNullable).length, 0)} |`);
    lines.push('');
  }

  // Table of Contents
  if (opts.includeTOC) {
    lines.push('## 📑 Table of Contents');
    lines.push('');
    tables.forEach((t, i) => {
      lines.push(`${i + 1}. [${t.tableName}](#${t.tableName.toLowerCase()}) — ${t.columns.length} columns`);
    });
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Relationships Overview
  if (opts.includeRelationships) {
    lines.push('## 🔗 Relationships Overview');
    lines.push('');
    lines.push('### Foreign Key Relationships');
    lines.push('');
    lines.push('| Table | Column | References | Type |');
    lines.push('|-------|--------|------------|------|');

    for (const table of tables) {
      for (const fk of table.foreignKeys) {
        const col = table.columns.find(
          (c) => c.name.toLowerCase() === fk.columnName.toLowerCase()
        );
        const nullable = col?.isNullable ? 'Optional' : 'Required';
        lines.push(
          `| ${table.tableName} | ${fk.columnName} | ${fk.referencesTable}.${fk.referencesColumn} | ${nullable} |`
        );
      }
    }

    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Detailed Table Documentation
  lines.push('## 📋 Table Details');
  lines.push('');

  for (const table of tables) {
    lines.push(`### ${table.tableName}`);
    lines.push('');
    lines.push(`**Schema:** \`${table.schemaName}\``);
    lines.push(`**Columns:** ${table.columns.length}`);
    lines.push(`**Foreign Keys:** ${table.foreignKeys.length}`);
    lines.push('');

    // Column table
    lines.push('| # | Column | Data Type | Nullable | PK | FK | Default |');
    lines.push('|---|--------|-----------|----------|----|----|---------|');

    table.columns.forEach((col, i) => {
      const fk = table.foreignKeys.find(
        (f) => f.columnName.toLowerCase() === col.name.toLowerCase()
      );
      const fkStr = fk ? `→ ${fk.referencesTable}` : '';
      const typeStr = col.maxLength
        ? `${col.dataType}(${col.maxLength})`
        : col.dataType;

      lines.push(
        `| ${i + 1} | \`${col.name}\` | ${typeStr} | ${col.isNullable ? '✅' : '❌'} | ${col.isPrimaryKey ? '🔑' : ''} | ${fkStr} | ${col.defaultValue || ''} |`
      );
    });

    lines.push('');

    // Foreign Keys detail
    if (table.foreignKeys.length > 0) {
      lines.push('#### Relationships');
      lines.push('');
      for (const fk of table.foreignKeys) {
        lines.push(
          `- **${fk.columnName}** → \`${fk.referencesTable}.${fk.referencesColumn}\`${fk.constraintName ? ` _(${fk.constraintName})_` : ''}`
        );
      }
      lines.push('');
    }

    // Indexes
    if (table.indexes && table.indexes.length > 0) {
      lines.push('#### Indexes');
      lines.push('');
      lines.push('| Index Name | Columns | Unique |');
      lines.push('|------------|---------|--------|');
      for (const idx of table.indexes) {
        lines.push(`| ${idx.name} | ${idx.columns.join(', ')} | ${idx.isUnique ? '✅' : '❌'} |`);
      }
      lines.push('');
    }

    // Source DDL
    if (opts.includeDDL && table.sourceDDL) {
      lines.push('#### Source DDL');
      lines.push('');
      lines.push('```sql');
      lines.push(table.sourceDDL);
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Summary Statistics
  if (opts.includeStatistics) {
    lines.push('## 📈 Summary Statistics');
    lines.push('');
    lines.push('### Data Types Distribution');
    lines.push('');

    const typeCounts: Record<string, number> = {};
    for (const table of tables) {
      for (const col of table.columns) {
        typeCounts[col.dataType] = (typeCounts[col.dataType] || 0) + 1;
      }
    }

    lines.push('| Data Type | Count |');
    lines.push('|-----------|-------|');
    for (const [type, count] of Object.entries(typeCounts).sort(
      (a, b) => b[1] - a[1]
    )) {
      lines.push(`| ${type} | ${count} |`);
    }
    lines.push('');

    lines.push('### Tables by Column Count');
    lines.push('');
    const sortedByColumns = [...tables].sort(
      (a, b) => b.columns.length - a.columns.length
    );
    lines.push('| Table | Columns |');
    lines.push('|-------|---------|');
    for (const t of sortedByColumns.slice(0, 10)) {
      lines.push(`| ${t.tableName} | ${t.columns.length} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate documentation for a single table
 */
export function generateTableDocumentation(table: TableDef): string {
  return generateDocumentation([table], table.tableName, {
    includeTOC: false,
    includeRelationships: false,
    includeStatistics: false,
  });
}

/**
 * Generate data dictionary in CSV format
 */
export function generateDataDictionaryCSV(tables: TableDef[]): string {
  const headers = [
    'Table Name',
    'Schema',
    'Column Name',
    'Data Type',
    'Max Length',
    'Nullable',
    'Primary Key',
    'Foreign Key',
    'FK Table',
    'FK Column',
    'Default Value',
    'Identity',
  ];

  const rows: string[][] = [];

  for (const table of tables) {
    for (const col of table.columns) {
      const fk = table.foreignKeys.find(
        (f) => f.columnName.toLowerCase() === col.name.toLowerCase()
      );

      rows.push([
        table.tableName,
        table.schemaName,
        col.name,
        col.dataType,
        col.maxLength || '',
        col.isNullable ? 'Yes' : 'No',
        col.isPrimaryKey ? 'Yes' : 'No',
        fk ? 'Yes' : 'No',
        fk?.referencesTable || '',
        fk?.referencesColumn || '',
        col.defaultValue || '',
        col.isIdentity ? 'Yes' : 'No',
      ]);
    }
  }

  const csvRows = [headers, ...rows].map((row) =>
    row.map((cell) => (cell.includes(',') || cell.includes('"') ? `"${cell.replace(/"/g, '""')}"` : cell)).join(',')
  );

  return csvRows.join('\n');
}

/**
 * Generate JSON schema documentation
 */
export function generateJSONSchema(tables: TableDef[]): Record<string, unknown> {
  const schema: Record<string, unknown> = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'Database Schema',
    type: 'object',
    properties: {} as Record<string, unknown>,
  };

  for (const table of tables) {
    const tableSchema: Record<string, unknown> = {
      type: 'object',
      title: table.tableName,
      properties: {} as Record<string, unknown>,
      required: [] as string[],
    };

    for (const col of table.columns) {
      const colSchema: Record<string, unknown> = {
        type: mapToJSONType(col.dataType),
        description: `Column: ${col.name}`,
      };

      if (col.maxLength) {
        colSchema.maxLength = parseInt(col.maxLength) || undefined;
      }

      if (col.defaultValue) {
        colSchema.default = col.defaultValue;
      }

      (tableSchema.properties as Record<string, unknown>)[col.name] = colSchema;

      if (!col.isNullable) {
        (tableSchema.required as string[]).push(col.name);
      }
    }

    (schema.properties as Record<string, unknown>)[table.tableName] = tableSchema;
  }

  return schema;
}

/**
 * Generate OpenAPI/Swagger schema from tables
 */
export function generateOpenAPISchema(
  tables: TableDef[],
  apiVersion: string = '1.0.0'
): Record<string, unknown> {
  const schema: Record<string, unknown> = {
    openapi: '3.0.0',
    info: {
      title: 'Database API',
      version: apiVersion,
      description: 'Auto-generated API from database schema',
    },
    paths: {} as Record<string, unknown>,
    components: {
      schemas: {} as Record<string, unknown>,
    },
  };

  // Generate schemas for each table
  for (const table of tables) {
    const modelName = toPascalSingular(table.tableName);
    const schemaDef: Record<string, unknown> = {
      type: 'object',
      properties: {} as Record<string, unknown>,
      required: [] as string[],
    };

    for (const col of table.columns) {
      const colSchema: Record<string, unknown> = {
        type: mapToJSONType(col.dataType),
      };

      if (col.maxLength) {
        colSchema.maxLength = parseInt(col.maxLength) || undefined;
      }

      if (col.dataType === 'UNIQUEIDENTIFIER') {
        colSchema.format = 'uuid';
      } else if (col.dataType === 'DATETIME' || col.dataType === 'DATETIME2') {
        colSchema.format = 'date-time';
      }

      (schemaDef.properties as Record<string, unknown>)[col.name] = colSchema;

      if (!col.isNullable && !col.isPrimaryKey) {
        (schemaDef.required as string[]).push(col.name);
      }
    }

    (schema.components as Record<string, unknown>).schemas[modelName] = schemaDef;

    // Generate paths
    const basePath = `/api/${toKebabCase(table.tableName)}`;

    (schema.paths as Record<string, unknown>)[basePath] = {
      get: {
        summary: `List all ${modelName}`,
        responses: {
          '200': {
            description: 'A list of records',
            content: {
              'application/json': {
                schema: {
                  type: 'array',
                  items: { $ref: `#/components/schemas/${modelName}` },
                },
              },
            },
          },
        },
      },
      post: {
        summary: `Create a new ${modelName}`,
        requestBody: {
          content: {
            'application/json': {
              schema: { $ref: `#/components/schemas/${modelName}` },
            },
          },
        },
        responses: {
          '201': {
            description: 'Created',
          },
        },
      },
    };

    (schema.paths as Record<string, unknown>)[`${basePath}/{id}`] = {
      get: {
        summary: `Get a ${modelName} by ID`,
        parameters: [
          {
            name: 'id',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        responses: {
          '200': {
            description: 'A single record',
            content: {
              'application/json': {
                schema: { $ref: `#/components/schemas/${modelName}` },
              },
            },
          },
          '404': {
            description: 'Not found',
          },
        },
      },
      put: {
        summary: `Update a ${modelName}`,
        parameters: [
          {
            name: 'id',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        requestBody: {
          content: {
            'application/json': {
              schema: { $ref: `#/components/schemas/${modelName}` },
            },
          },
        },
        responses: {
          '200': {
            description: 'Updated',
          },
        },
      },
      delete: {
        summary: `Delete a ${modelName}`,
        parameters: [
          {
            name: 'id',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        responses: {
          '204': {
            description: 'Deleted',
          },
        },
      },
    };
  }

  return schema;
}

/**
 * Generate user stories from tables
 */
export function generateUserStories(
  tables: TableDef[],
  prefix: string = 'US'
): UserStory[] {
  const stories: UserStory[] = [];
  let counter = 1;

  for (const table of tables) {
    const modelName = toPascalSingular(table.tableName);
    const requiredCols = table.columns.filter(
      (c) => !c.isNullable && !c.isPrimaryKey
    );

    // Create story
    stories.push({
      id: `${prefix}-${String(counter++).padStart(3, '0')}`,
      title: `Create ${modelName}`,
      role: 'User',
      feature: `create a new ${modelName} record`,
      benefit: `I can add new ${modelName} data to the system`,
      acceptanceCriteria: [
        `I can access the create ${modelName} form`,
        `I can fill in all required fields: ${requiredCols.map((c) => c.name).join(', ')}`,
        'I see validation errors for invalid input',
        'I receive a success message after creation',
        'The new record appears in the list',
      ],
      priority: 'must_have',
      storyPoints: 3,
      tables: [table.tableName],
    });

    // Read/List story
    stories.push({
      id: `${prefix}-${String(counter++).padStart(3, '0')}`,
      title: `List ${modelName} Records`,
      role: 'User',
      feature: `view a list of ${modelName} records`,
      benefit: `I can see all ${modelName} data at a glance`,
      acceptanceCriteria: [
        `I can access the ${modelName} list page`,
        'I can see all records in a table format',
        'I can sort by any column',
        'I can paginate through results',
        'I can search/filter records',
      ],
      priority: 'must_have',
      storyPoints: 2,
      tables: [table.tableName],
    });

    // Update story
    stories.push({
      id: `${prefix}-${String(counter++).padStart(3, '0')}`,
      title: `Update ${modelName}`,
      role: 'User',
      feature: `edit an existing ${modelName} record`,
      benefit: `I can keep ${modelName} data accurate and up-to-date`,
      acceptanceCriteria: [
        `I can select a ${modelName} record to edit`,
        'I can modify any editable field',
        'I see validation errors for invalid input',
        'I receive a success message after saving',
        'The changes are reflected immediately',
      ],
      priority: 'must_have',
      storyPoints: 2,
      tables: [table.tableName],
    });

    // Delete story
    stories.push({
      id: `${prefix}-${String(counter++).padStart(3, '0')}`,
      title: `Delete ${modelName}`,
      role: 'User',
      feature: `delete a ${modelName} record`,
      benefit: `I can remove outdated or incorrect ${modelName} data`,
      acceptanceCriteria: [
        `I can select a ${modelName} record to delete`,
        'I see a confirmation dialog',
        'I must confirm before deletion',
        'I receive a success message after deletion',
        'The record is removed from the list',
      ],
      priority: 'should_have',
      storyPoints: 1,
      tables: [table.tableName],
    });

    // Search story
    stories.push({
      id: `${prefix}-${String(counter++).padStart(3, '0')}`,
      title: `Search ${modelName}`,
      role: 'User',
      feature: `search for ${modelName} records`,
      benefit: `I can quickly find specific ${modelName} data`,
      acceptanceCriteria: [
        'I can enter search terms',
        'Results update as I type (optional)',
        'I can clear search to see all records',
        'Search works across relevant columns',
      ],
      priority: 'should_have',
      storyPoints: 2,
      tables: [table.tableName],
    });
  }

  return stories;
}

/**
 * Generate user stories in Markdown format
 */
export function userStoriesToMarkdown(stories: UserStory[]): string {
  const lines: string[] = [];

  lines.push('# User Stories');
  lines.push('');
  lines.push(`> Total Stories: ${stories.length}`);
  lines.push('');

  for (const story of stories) {
    lines.push(`## ${story.id}: ${story.title}`);
    lines.push('');
    lines.push(`**As a** ${story.role}`);
    lines.push(`**I want to** ${story.feature}`);
    lines.push(`**So that** ${story.benefit}`);
    lines.push('');
    lines.push(`**Priority:** ${story.priority.replace('_', ' ')}`);
    lines.push(`**Story Points:** ${story.storyPoints}`);
    lines.push(`**Tables:** ${story.tables.join(', ')}`);
    lines.push('');
    lines.push('### Acceptance Criteria');
    lines.push('');
    for (const criteria of story.acceptanceCriteria) {
      lines.push(`- [ ] ${criteria}`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate module documentation
 */
export function generateModuleDocumentation(
  modules: ModuleDef[]
): string {
  const lines: string[] = [];

  lines.push('# Module Documentation');
  lines.push('');

  // Group by layer
  const layerGroups = new Map<number, ModuleDef[]>();
  for (const mod of modules) {
    const group = layerGroups.get(mod.layer) || [];
    group.push(mod);
    layerGroups.set(mod.layer, group);
  }

  for (const [layer, mods] of layerGroups) {
    lines.push(`## Layer ${layer}`);
    lines.push('');

    for (const mod of mods) {
      lines.push(`### ${mod.name}`);
      lines.push('');
      lines.push(`**Key:** \`${mod.key}\``);
      lines.push(`**Description:** ${mod.description}`);
      lines.push(`**Priority:** ${mod.priority}`);
      lines.push(`**Estimated Days:** ${mod.estimatedDays}`);
      lines.push(`**Revenue Generating:** ${mod.revenue ? 'Yes' : 'No'}`);
      lines.push('');

      lines.push('**Tables:**');
      lines.push('');
      for (const table of mod.tables) {
        lines.push(`- ${table}`);
      }
      lines.push('');

      lines.push('**Features:**');
      lines.push('');
      for (const feature of mod.features) {
        lines.push(`- ${feature}`);
      }
      lines.push('');

      lines.push('**Dependencies:**');
      lines.push('');
      if (mod.dependsOn.length === 0) {
        lines.push('- None (foundation module)');
      } else {
        for (const dep of mod.dependsOn) {
          lines.push(`- ${dep}`);
        }
      }
      lines.push('');

      lines.push('---');
      lines.push('');
    }
  }

  return lines.join('\n');
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Map SQL data type to JSON Schema type
 */
function mapToJSONType(dataType: string): string {
  const type = dataType.toUpperCase();

  if (['INT', 'BIGINT', 'SMALLINT', 'TINYINT'].includes(type)) {
    return 'integer';
  }

  if (['DECIMAL', 'NUMERIC', 'FLOAT', 'REAL', 'MONEY', 'SMALLMONEY'].includes(type)) {
    return 'number';
  }

  if (['BIT'].includes(type)) {
    return 'boolean';
  }

  if (['DATETIME', 'DATETIME2', 'DATE', 'SMALLDATETIME', 'DATETIMEOFFSET'].includes(type)) {
    return 'string';
  }

  return 'string';
}

/**
 * Convert to PascalCase singular
 */
function toPascalSingular(name: string): string {
  let singular = name;

  if (singular.endsWith('ies')) {
    singular = singular.slice(0, -3) + 'y';
  } else if (singular.endsWith('ses') || singular.endsWith('xes')) {
    singular = singular.slice(0, -2);
  } else if (
    singular.endsWith('s') &&
    !singular.endsWith('ss') &&
    !singular.endsWith('us')
  ) {
    singular = singular.slice(0, -1);
  }

  return singular.charAt(0).toUpperCase() + singular.slice(1);
}

/**
 * Convert to kebab-case
 */
function toKebabCase(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}
