'use client'

export interface PDFColumn {
  header: string
  key: string
  width?: number
  align?: 'left' | 'right' | 'center'
}

export interface PDFExportOptions {
  title: string
  subtitle?: string
  companyInfo?: {
    companyName?: string
    address?: string
    phone?: string
    ntn?: string
  }
  columns: PDFColumn[]
  rows: string[][]
  summaryRows?: string[][]
  filename?: string
}

const PAGE_WIDTH = 210 // A4 width in mm
const MARGIN = 15
const USABLE_WIDTH = PAGE_WIDTH - MARGIN * 2
const LINE_HEIGHT = 5
const HEADER_FONT_SIZE = 8
const DATA_FONT_SIZE = 7
const TITLE_FONT_SIZE = 16
const SUBTITLE_FONT_SIZE = 10
const SMALL_FONT_SIZE = 8
const FOOTER_FONT_SIZE = 7

function formatDate(): string {
  return new Date().toLocaleDateString('en-PK', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

function formatDateTime(): string {
  return new Date().toLocaleDateString('en-PK', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function drawHeader(doc: any, y: number, columns: PDFColumn[], colWidths: number[]): number {
  // Gray background
  doc.setFillColor(240, 240, 240)
  doc.rect(MARGIN, y - 3, USABLE_WIDTH, LINE_HEIGHT + 1, 'F')

  // Header text
  doc.setFontSize(HEADER_FONT_SIZE)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(60, 60, 60)

  let x = MARGIN
  for (let i = 0; i < columns.length; i++) {
    const col = columns[i]
    const w = colWidths[i]
    let textX = x + 2
    if (col.align === 'right') {
      textX = x + w - 2
    } else if (col.align === 'center') {
      textX = x + w / 2
    }
    doc.text(col.header, textX, y, { align: col.align === 'right' ? 'right' : col.align === 'center' ? 'center' : 'left' })
    x += w
  }

  return y + LINE_HEIGHT + 1
}

function drawDataRows(doc: any, start_y: number, columns: PDFColumn[], colWidths: number[], rows: string[][], maxPageHeight: number): number {
  let y = start_y
  doc.setFontSize(DATA_FONT_SIZE)
  doc.setFont('helvetica', 'normal')

  for (let r = 0; r < rows.length; r++) {
    // Page break check
    if (y > maxPageHeight - 20) {
      doc.addPage()
      y = MARGIN
      // Re-draw header on new page
      doc.setDrawColor(200, 200, 200)
      doc.line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5)
      y = drawHeader(doc, y, columns, colWidths)
      y += 2
    }

    // Alternate row background
    if (r % 2 === 1) {
      doc.setFillColor(249, 249, 249)
      doc.rect(MARGIN, y - 3, USABLE_WIDTH, LINE_HEIGHT, 'F')
    }

    doc.setTextColor(40, 40, 40)

    const row = rows[r]
    let x = MARGIN
    for (let c = 0; c < columns.length; c++) {
      const col = columns[c]
      const w = colWidths[c]
      const text = c < row.length ? String(row[c] || '') : ''
      // Truncate text that might overflow
      const maxChars = Math.floor((w - 4) / 1.5)
      const truncated = text.length > maxChars ? text.substring(0, maxChars - 2) + '..' : text

      let textX = x + 2
      const align = col.align || 'left'
      if (align === 'right') {
        textX = x + w - 2
      } else if (align === 'center') {
        textX = x + w / 2
      }
      doc.text(truncated, textX, y, { align: align === 'right' ? 'right' : align === 'center' ? 'center' : 'left' })
      x += w
    }
    y += LINE_HEIGHT
  }

  return y
}

function drawFooter(doc: any, pageNumber: number, totalPages: number) {
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(FOOTER_FONT_SIZE)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(160, 160, 160)

  // Separator line
  doc.setDrawColor(220, 220, 220)
  doc.line(MARGIN, pageHeight - 15, PAGE_WIDTH - MARGIN, pageHeight - 15)

  doc.text('Generated by AccuBooks Accounting System', MARGIN, pageHeight - 10)
  doc.text(formatDateTime(), PAGE_WIDTH / 2, pageHeight - 10, { align: 'center' })
  doc.text(`Page ${pageNumber} of ${totalPages}`, PAGE_WIDTH - MARGIN, pageHeight - 10, { align: 'right' })
}

export async function exportToPDF(options: PDFExportOptions): Promise<void> {
  try {
    // Dynamic import jspdf
    const { default: jsPDF } = await import('jspdf')

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const pageHeight = doc.internal.pageSize.getHeight()
    const maxPageHeight = pageHeight - MARGIN

    // Calculate column widths based on flex values
    const totalFlex = options.columns.reduce((sum, col) => sum + (col.width || 1), 0)
    const colWidths = options.columns.map(col => ((col.width || 1) / totalFlex) * USABLE_WIDTH)

    // --- Page 1: Title & Company Info ---
    let y = MARGIN

    // Title
    doc.setFontSize(TITLE_FONT_SIZE)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    doc.text(options.title, MARGIN, y)
    y += 7

    // Subtitle
    if (options.subtitle) {
      doc.setFontSize(SUBTITLE_FONT_SIZE)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      doc.text(options.subtitle, MARGIN, y)
      y += 6
    }

    // Company info (right-aligned)
    if (options.companyInfo) {
      doc.setFontSize(SMALL_FONT_SIZE)
      doc.setTextColor(100, 100, 100)
      const info = options.companyInfo
      if (info.companyName) {
        doc.text(info.companyName, PAGE_WIDTH - MARGIN, MARGIN, { align: 'right' })
      }
      let infoY = MARGIN + 4
      if (info.address) {
        doc.text(info.address, PAGE_WIDTH - MARGIN, infoY, { align: 'right' })
        infoY += 4
      }
      if (info.phone) {
        doc.text(`Ph: ${info.phone}`, PAGE_WIDTH - MARGIN, infoY, { align: 'right' })
        infoY += 4
      }
      if (info.ntn) {
        doc.text(`NTN: ${info.ntn}`, PAGE_WIDTH - MARGIN, infoY, { align: 'right' })
      }
    }

    // Date line
    y += 2
    doc.setFontSize(SMALL_FONT_SIZE)
    doc.setTextColor(128, 128, 128)
    doc.text(`Date: ${formatDate()}`, MARGIN, y)
    y += 3

    // Separator line
    doc.setDrawColor(200, 200, 200)
    doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y)
    y += 5

    // --- Table Header ---
    y = drawHeader(doc, y, options.columns, colWidths)
    y += 2

    // --- Data Rows ---
    // We need to track pages for footer
    const pages: number[] = [1] // Track y positions where pages start
    y = drawDataRows(doc, y, options.columns, colWidths, options.rows, maxPageHeight)

    // Count total pages (doc has already been building pages)
    const totalPages = doc.getNumberOfPages()

    // --- Summary Rows ---
    if (options.summaryRows && options.summaryRows.length > 0) {
      // Check if we need a new page
      const summaryHeight = (options.summaryRows.length * (LINE_HEIGHT + 2)) + 8
      if (y + summaryHeight > maxPageHeight) {
        doc.addPage()
        y = MARGIN
        doc.setDrawColor(200, 200, 200)
        doc.line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5)
        y = drawHeader(doc, y, options.columns, colWidths)
        y += 2
      }

      y += 2
      // Separator line before summary
      doc.setDrawColor(100, 100, 100)
      doc.setLineWidth(0.3)
      doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y)
      doc.setLineWidth(0.2)
      y += 4

      doc.setFontSize(DATA_FONT_SIZE)
      for (let r = 0; r < options.summaryRows.length; r++) {
        const row = options.summaryRows[r]
        const isLastRow = r === options.summaryRows.length - 1

        // Bold for last summary row (grand total)
        doc.setFont('helvetica', isLastRow ? 'bold' : 'normal')

        // Light background for summary rows
        if (isLastRow) {
          doc.setFillColor(240, 245, 240)
          doc.rect(MARGIN, y - 3, USABLE_WIDTH, LINE_HEIGHT + 1, 'F')
        } else {
          doc.setFillColor(250, 250, 250)
          doc.rect(MARGIN, y - 3, USABLE_WIDTH, LINE_HEIGHT, 'F')
        }

        doc.setTextColor(isLastRow ? 20 : 60, isLastRow ? 60 : 60, isLastRow ? 20 : 60)

        let x = MARGIN
        for (let c = 0; c < options.columns.length; c++) {
          const col = options.columns[c]
          const w = colWidths[c]
          const text = c < row.length ? String(row[c] || '') : ''
          const align = col.align || 'left'

          let textX = x + 2
          if (align === 'right') {
            textX = x + w - 2
          } else if (align === 'center') {
            textX = x + w / 2
          }
          doc.text(text, textX, y, { align: align === 'right' ? 'right' : align === 'center' ? 'center' : 'left' })
          x += w
        }
        y += LINE_HEIGHT + 1
      }
    }

    // --- Draw footers on all pages ---
    const finalTotalPages = doc.getNumberOfPages()
    for (let p = 1; p <= finalTotalPages; p++) {
      doc.setPage(p)
      drawFooter(doc, p, finalTotalPages)
    }

    // Save
    const filename = options.filename || `${options.title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`
    doc.save(filename)
  } catch (error) {
    console.error('PDF export error:', error)
    // Re-throw with a user-friendly message
    throw new Error('Failed to generate PDF. Please try again.')
  }
}

/**
 * Helper to format a number as PKR currency string for PDF cells
 */
export function pdfFormatPKR(amount: number | string): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : amount
  if (isNaN(num)) return String(amount)
  return new Intl.NumberFormat('en-PK', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(num)
}

/**
 * Helper to format a date string for PDF cells
 */
export function pdfFormatDate(dateStr: string | Date): string {
  try {
    const date = typeof dateStr === 'string' ? new Date(dateStr) : dateStr
    return date.toLocaleDateString('en-PK', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    })
  } catch {
    return String(dateStr)
  }
}
