// =============================================================================
// Schema Toolkit - Prisma Schema Generator
// =============================================================================

import { TableDef, ColumnDef, GeneratorOptions } from './types';

/**
 * SQL Server to Prisma type mapping
 */
const TYPE_MAP: Record<string, string> = {
  UNIQUEIDENTIFIER: 'String',
  NVARCHAR: 'String',
  VARCHAR: 'String',
  NCHAR: 'String',
  CHAR: 'String',
  TEXT: 'String',
  NTEXT: 'String',
  INT: 'Int',
  BIGINT: 'BigInt',
  SMALLINT: 'Int',
  TINYINT: 'Int',
  BIT: 'Boolean',
  DECIMAL: 'Decimal',
  NUMERIC: 'Decimal',
  FLOAT: 'Float',
  REAL: 'Float',
  MONEY: 'Decimal',
  SMALLMONEY: 'Decimal',
  DATETIME: 'DateTime',
  DATETIME2: 'DateTime',
  SMALLDATETIME: 'DateTime',
  DATE: 'DateTime',
  TIME: 'String',
  DATETIMEOFFSET: 'DateTime',
  IMAGE: 'Bytes',
  VARBINARY: 'Bytes',
  BINARY: 'Bytes',
  XML: 'String',
  JSON: 'Json',
  SQL_VARIANT: 'Json',
  GEOMETRY: 'String',
  GEOGRAPHY: 'String',
  HIERARCHYID: 'String',
  TIMESTAMP: 'Bytes',
  ROWVERSION: 'Bytes',
};

/**
 * Generate Prisma schema from parsed tables
 */
export function generatePrismaSchema(
  tables: TableDef[],
  options: GeneratorOptions = {
    provider: 'sqlite',
    includeRelations: true,
    includeAuditFields: true,
    useUUID: true,
    softDelete: false,
  }
): string {
  const lines: string[] = [];

  // Header
  lines.push(`// ─── Auto-generated by Schema Toolkit ───`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`// Tables: ${tables.length}`);
  lines.push(`// Provider: ${options.provider}`);
  lines.push('');

  // Generator
  lines.push(`generator client {`);
  lines.push(`  provider = "prisma-client-js"`);
  lines.push(`}`);
  lines.push('');

  // Datasource
  lines.push(`datasource db {`);
  lines.push(`  provider = "${options.provider}"`);

  if (options.provider === 'sqlite') {
    lines.push(`  url      = "file:./dev.db"`);
  } else {
    lines.push(`  url      = env("DATABASE_URL")`);
  }

  lines.push(`}`);
  lines.push('');

  // Build a lookup: tableName → modelName
  const modelMap = new Map<string, string>();
  tables.forEach((t) => {
    modelMap.set(t.tableName.toLowerCase(), toPascalSingular(t.tableName));
  });

  // Generate each model
  for (const table of tables) {
    const modelName = modelMap.get(table.tableName.toLowerCase())!;
    lines.push(`model ${modelName} {`);

    // Columns
    for (const col of table.columns) {
      const fieldName = toCamelCase(col.name);
      let prismaType = TYPE_MAP[col.dataType] || 'String';

      const attrs: string[] = [];

      // Primary key handling
      if (col.isPrimaryKey) {
        attrs.push('@id');
        if (col.dataType === 'UNIQUEIDENTIFIER' || options.useUUID) {
          if (col.defaultValue?.toLowerCase().includes('newid')) {
            attrs.push('@default(uuid())');
          } else if (!col.isIdentity) {
            attrs.push('@default(uuid())');
          }
        } else if (col.isIdentity) {
          attrs.push('@default(autoincrement())');
        }
      }

      // Nullable
      if (col.isNullable && !col.isPrimaryKey) {
        prismaType += '?';
      }

      // Default value
      if (col.defaultValue && !col.isPrimaryKey) {
        const def = convertDefault(col.defaultValue, col.dataType);
        if (def) attrs.push(`@default(${def})`);
      }

      // Map to original column name if different
      if (fieldName !== col.name) {
        attrs.push(`@map("${col.name}")`);
      }

      // Database-specific type
      if (options.provider !== 'sqlite' && col.maxLength) {
        if (col.dataType === 'NVARCHAR' || col.dataType === 'VARCHAR') {
          const length = col.maxLength === 'MAX' ? '191' : col.maxLength;
          attrs.push(`@db.${options.provider === 'postgresql' ? 'VarChar' : 'NVarChar'}(${length})`);
        }
      }

      const attrStr = attrs.length ? '  ' + attrs.join(' ') : '';
      lines.push(`  ${padRight(fieldName, 24)} ${padRight(prismaType, 12)}${attrStr}`);
    }

    // Unique constraints
    const uniqueColumns = findUniqueColumns(table);
    for (const unique of uniqueColumns) {
      if (unique.columns.length === 1) {
        const col = table.columns.find(
          (c) => c.name.toLowerCase() === unique.columns[0].toLowerCase()
        );
        if (col && !col.isPrimaryKey) {
          lines.push(`  @@unique([${toCamelCase(col.name)}])`);
        }
      } else {
        const fields = unique.columns.map(toCamelCase).join(', ');
        lines.push(`  @@unique([${fields}])`);
      }
    }

    // Indexes
    if (table.indexes && table.indexes.length > 0) {
      for (const idx of table.indexes) {
        if (!idx.isUnique) {
          const fields = idx.columns.map(toCamelCase).join(', ');
          lines.push(`  @@index([${fields}])`);
        }
      }
    }

    // Relation fields (from foreign keys)
    if (options.includeRelations && table.foreignKeys.length > 0) {
      lines.push('');
      lines.push(`  // ── Relations ──`);
    }

    if (options.includeRelations) {
      for (const fk of table.foreignKeys) {
        const refModelName = modelMap.get(fk.referencesTable.toLowerCase());
        if (!refModelName) continue;

        const fieldName = toCamelCase(fk.referencesTable);
        const fkField = toCamelCase(fk.columnName);

        // Check if column is nullable
        const col = table.columns.find(
          (c) => c.name.toLowerCase() === fk.columnName.toLowerCase()
        );
        const optional = col?.isNullable ? '?' : '';

        const refField = toCamelCase(fk.referencesColumn);

        lines.push(
          `  ${padRight(fieldName, 24)} ${refModelName}${optional}  @relation(fields: [${fkField}], references: [${refField}], onDelete: NoAction, onUpdate: NoAction)`
        );
      }

      // Reverse relations (has-many)
      const reverseRels = findReverseRelations(table, tables);
      for (const rev of reverseRels) {
        const revModel = modelMap.get(rev.toLowerCase());
        if (revModel) {
          const fieldName = toCamelCase(toPascalSingular(rev)) + 's';
          lines.push(`  ${padRight(fieldName, 24)} ${revModel}[]`);
        }
      }
    }

    // Map to original table name
    lines.push('');
    lines.push(`  @@map("${table.tableName}")`);
    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate Prisma schema for a single table
 */
export function generateSingleModel(
  table: TableDef,
  options: GeneratorOptions = {
    provider: 'sqlite',
    includeRelations: true,
    includeAuditFields: true,
    useUUID: true,
    softDelete: false,
  }
): string {
  return generatePrismaSchema([table], options);
}

/**
 * Generate Prisma enum definitions from lookup tables
 */
export function generateEnums(
  lookupTables: TableDef[]
): string {
  const lines: string[] = [];

  for (const table of lookupTables) {
    const enumName = toPascalSingular(table.tableName);
    lines.push(`enum ${enumName} {`);

    // Find name/value columns
    const nameCol = table.columns.find(
      (c) =>
        c.name.toLowerCase() === 'name' ||
        c.name.toLowerCase().endsWith('name')
    );

    if (nameCol) {
      // This would need actual values to populate the enum
      lines.push(`  // Values would be populated from data`);
      lines.push(`  UNKNOWN`);
    }

    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Find unique constraints in table
 */
function findUniqueColumns(
  table: TableDef
): { name: string; columns: string[] }[] {
  const uniques: { name: string; columns: string[] }[] = [];

  // Check for UNIQUE constraints in checkConstraints
  if (table.checkConstraints) {
    for (const check of table.checkConstraints) {
      if (check.name?.toLowerCase().includes('unique')) {
        // Extract column names from constraint
        const match = check.expression?.match(/\[?(\w+)\]?/g);
        if (match) {
          uniques.push({
            name: check.name || '',
            columns: match.map((c) => c.replace(/[\[\]]/g, '')),
          });
        }
      }
    }
  }

  // Check indexes for unique
  if (table.indexes) {
    for (const idx of table.indexes) {
      if (idx.isUnique && idx.columns.length > 0) {
        uniques.push({
          name: idx.name,
          columns: idx.columns,
        });
      }
    }
  }

  return uniques;
}

/**
 * Find reverse relations (tables that reference this table)
 */
function findReverseRelations(
  current: TableDef,
  all: TableDef[]
): string[] {
  const result: string[] = [];

  for (const t of all) {
    if (t.tableName === current.tableName) continue;

    for (const fk of t.foreignKeys) {
      if (fk.referencesTable.toLowerCase() === current.tableName.toLowerCase()) {
        result.push(t.tableName);
      }
    }
  }

  return [...new Set(result)];
}

/**
 * Convert SQL Server default value to Prisma default
 */
function convertDefault(val: string, dataType: string): string | null {
  const v = val.replace(/[()]/g, '').trim();

  // Functions
  if (v.toLowerCase() === 'getdate' || v.toLowerCase() === 'getutcdate') {
    return 'now()';
  }
  if (v.toLowerCase() === 'newid' || v.toLowerCase() === 'newsequentialid') {
    return 'uuid()';
  }

  // Boolean
  if (v === '1' && dataType === 'BIT') return 'true';
  if (v === '0' && dataType === 'BIT') return 'false';

  // Numbers
  if (/^-?\d+$/.test(v)) return v;
  if (/^-?\d+\.\d+$/.test(v)) return v;

  // String literals (remove quotes if present)
  if (/^N?'(.*)'$/.test(v)) {
    const match = v.match(/^N?'(.*)'$/);
    return match ? `"${match[1]}"` : null;
  }

  // Default to null for complex expressions
  return null;
}

/**
 * Convert table name to PascalCase singular
 */
function toPascalSingular(name: string): string {
  let singular = name;

  // Common plural → singular rules
  if (singular.endsWith('ies')) {
    singular = singular.slice(0, -3) + 'y';
  } else if (singular.endsWith('ses') || singular.endsWith('xes')) {
    singular = singular.slice(0, -2);
  } else if (
    singular.endsWith('s') &&
    !singular.endsWith('ss') &&
    !singular.endsWith('us') &&
    !singular.endsWith('is')
  ) {
    singular = singular.slice(0, -1);
  }

  return singular.charAt(0).toUpperCase() + singular.slice(1);
}

/**
 * Convert to camelCase
 */
function toCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/**
 * Pad string to fixed length
 */
function padRight(str: string, len: number): string {
  return str + ' '.repeat(Math.max(0, len - str.length));
}

/**
 * Generate model comparison between SQL and existing Prisma
 */
export function compareWithExistingPrisma(
  sqlTables: TableDef[],
  prismaContent: string
): {
  newTables: string[];
  modifiedTables: string[];
  removedTables: string[];
} {
  const sqlTableNames = new Set(
    sqlTables.map((t) => t.tableName.toLowerCase())
  );

  // Extract existing table names from Prisma schema
  const prismaTableRegex = /@@map\("(\w+)"\)/g;
  const prismaTableNames = new Set<string>();

  let match: RegExpExecArray | null;
  while ((match = prismaTableRegex.exec(prismaContent)) !== null) {
    prismaTableNames.add(match[1].toLowerCase());
  }

  const newTables: string[] = [];
  const modifiedTables: string[] = [];
  const removedTables: string[] = [];

  // Find new tables
  for (const table of sqlTables) {
    if (!prismaTableNames.has(table.tableName.toLowerCase())) {
      newTables.push(table.tableName);
    }
  }

  // Find removed tables
  for (const name of prismaTableNames) {
    if (!sqlTableNames.has(name)) {
      removedTables.push(name);
    }
  }

  return { newTables, modifiedTables, removedTables };
}

/**
 * Generate migration-safe Prisma schema with comments
 */
export function generatePrismaWithComments(
  tables: TableDef[],
  options: GeneratorOptions = {
    provider: 'sqlite',
    includeRelations: true,
    includeAuditFields: true,
    useUUID: true,
    softDelete: false,
  }
): string {
  const lines: string[] = [];

  lines.push(`// ─── Prisma Schema with Intelligence Comments ───`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`// Tables: ${tables.length}`);
  lines.push('');
  lines.push(`// ─── Statistics ───`);
  lines.push(`// Total Tables: ${tables.length}`);
  lines.push(`// Total Columns: ${tables.reduce((a, t) => a + t.columns.length, 0)}`);
  lines.push(`// Total FKs: ${tables.reduce((a, t) => a + t.foreignKeys.length, 0)}`);
  lines.push('');

  const baseSchema = generatePrismaSchema(tables, options);
  lines.push(baseSchema);

  return lines.join('\n');
}
