/**
 * ZIP BUILDER SERVICE
 * ===================
 * Creates properly structured ZIP files for project export.
 * Uses JSZip for reliable cross-platform ZIP creation with compression.
 */

import JSZip from 'jszip';
import fs from 'fs/promises';
import path from 'path';
import { existsSync } from 'fs';

// Export options
export interface ZipExportOptions {
  projectName: string;
  includeNodeModules?: boolean;
  includeGitIgnore?: boolean;
  includeEnvExample?: boolean;
  includeReadme?: boolean;
  compressionLevel?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  comment?: string;
}

// Export result
export interface ZipExportResult {
  success: boolean;
  buffer?: Buffer;
  size: number;
  fileCount: number;
  errors: string[];
  warnings: string[];
  manifest: ZipManifest;
}

// ZIP manifest
export interface ZipManifest {
  projectName: string;
  exportedAt: Date;
  files: {
    path: string;
    size: number;
    compressedSize?: number;
  }[];
  totalSize: number;
  compressedSize?: number;
  version: string;
}

// Files to always exclude
const DEFAULT_EXCLUDES = [
  'node_modules',
  '.next',
  '.git',
  'dist',
  'build',
  '.DS_Store',
  'Thumbs.db',
  '*.log',
  '.env',
  '.env.local',
  '.env.development.local',
  '.env.test.local',
  '.env.production.local'
];

/**
 * ZIP BUILDER CLASS
 */
export class ZipBuilder {
  private version = '1.0.0';

  /**
   * Create a ZIP file from a directory
   */
  async createFromDirectory(
    directoryPath: string,
    options: ZipExportOptions
  ): Promise<ZipExportResult> {
    const errors: string[] = [];
    const warnings: string[] = [];
    const manifestFiles: ZipManifest['files'] = [];
    let totalSize = 0;
    let fileCount = 0;

    try {
      // Validate directory exists
      if (!existsSync(directoryPath)) {
        return {
          success: false,
          size: 0,
          fileCount: 0,
          errors: [`Directory not found: ${directoryPath}`],
          warnings: [],
          manifest: this.createEmptyManifest(options.projectName)
        };
      }

      // Create JSZip instance
      const zip = new JSZip();

      // Determine excludes
      const excludes = options.includeNodeModules 
        ? DEFAULT_EXCLUDES.filter(e => e !== 'node_modules')
        : DEFAULT_EXCLUDES;

      // Add files to ZIP
      await this.addDirectoryToZip(
        zip.folder(options.projectName)!,
        directoryPath,
        '',
        excludes,
        manifestFiles,
        (size, count) => {
          totalSize += size;
          fileCount += count;
        }
      );

      // Add README if requested
      if (options.includeReadme) {
        const readme = await this.generateReadme(options);
        zip.folder(options.projectName)?.file('README.md', readme);
        manifestFiles.push({ path: 'README.md', size: readme.length });
        totalSize += readme.length;
        fileCount++;
      }

      // Add .env.example if requested
      if (options.includeEnvExample) {
        const envExample = await this.generateEnvExample();
        zip.folder(options.projectName)?.file('.env.example', envExample);
        manifestFiles.push({ path: '.env.example', size: envExample.length });
        totalSize += envExample.length;
        fileCount++;
      }

      // Add assembly instructions
      const instructions = this.generateInstructions(options);
      zip.folder(options.projectName)?.file('SETUP_INSTRUCTIONS.md', instructions);
      manifestFiles.push({ path: 'SETUP_INSTRUCTIONS.md', size: instructions.length });

      // Set ZIP comment
      if (options.comment) {
        zip.comment = options.comment;
      }

      // Generate ZIP buffer
      const buffer = await zip.generateAsync({
        type: 'nodebuffer',
        compression: 'DEFLATE',
        compressionOptions: {
          level: options.compressionLevel ?? 6
        },
        comment: `Generated by AI Enterprise Architect on ${new Date().toISOString()}`
      });

      // Create manifest
      const manifest: ZipManifest = {
        projectName: options.projectName,
        exportedAt: new Date(),
        files: manifestFiles,
        totalSize,
        compressedSize: buffer.length,
        version: this.version
      };

      // Add manifest to result
      const manifestJson = JSON.stringify(manifest, null, 2);
      manifestFiles.push({ path: 'export-manifest.json', size: manifestJson.length });

      return {
        success: true,
        buffer,
        size: buffer.length,
        fileCount,
        errors,
        warnings,
        manifest
      };
    } catch (error) {
      errors.push(`ZIP creation failed: ${error}`);
      return {
        success: false,
        size: 0,
        fileCount: 0,
        errors,
        warnings,
        manifest: this.createEmptyManifest(options.projectName)
      };
    }
  }

  /**
   * Create a ZIP file from individual files
   */
  async createFromFiles(
    files: { path: string; content: string | Buffer }[],
    options: ZipExportOptions
  ): Promise<ZipExportResult> {
    const errors: string[] = [];
    const warnings: string[] = [];
    const manifestFiles: ZipManifest['files'] = [];
    let totalSize = 0;

    try {
      const zip = new JSZip();
      const projectFolder = zip.folder(options.projectName);

      if (!projectFolder) {
        throw new Error('Failed to create project folder in ZIP');
      }

      for (const file of files) {
        const content = typeof file.content === 'string' 
          ? file.content 
          : file.content;
        
        projectFolder.file(file.path, content);
        
        const size = typeof file.content === 'string' 
          ? file.content.length 
          : file.content.length;
        
        manifestFiles.push({ path: file.path, size });
        totalSize += size;
      }

      // Add instructions
      const instructions = this.generateInstructions(options);
      projectFolder.file('SETUP_INSTRUCTIONS.md', instructions);
      manifestFiles.push({ path: 'SETUP_INSTRUCTIONS.md', size: instructions.length });

      // Generate ZIP
      const buffer = await zip.generateAsync({
        type: 'nodebuffer',
        compression: 'DEFLATE',
        compressionOptions: { level: options.compressionLevel ?? 6 }
      });

      const manifest: ZipManifest = {
        projectName: options.projectName,
        exportedAt: new Date(),
        files: manifestFiles,
        totalSize,
        compressedSize: buffer.length,
        version: this.version
      };

      return {
        success: true,
        buffer,
        size: buffer.length,
        fileCount: files.length + 1,
        errors,
        warnings,
        manifest
      };
    } catch (error) {
      errors.push(`ZIP creation failed: ${error}`);
      return {
        success: false,
        size: 0,
        fileCount: 0,
        errors,
        warnings,
        manifest: this.createEmptyManifest(options.projectName)
      };
    }
  }

  /**
   * Add directory contents to ZIP recursively
   */
  private async addDirectoryToZip(
    zipFolder: JSZip,
    basePath: string,
    relativePath: string,
    excludes: string[],
    manifestFiles: ZipManifest['files'],
    onProgress: (size: number, count: number) => void
  ): Promise<void> {
    const fullPath = path.join(basePath, relativePath);
    const entries = await fs.readdir(fullPath, { withFileTypes: true });

    for (const entry of entries) {
      // Check if excluded
      if (this.isExcluded(entry.name, excludes)) {
        continue;
      }

      const entryRelativePath = relativePath 
        ? `${relativePath}/${entry.name}` 
        : entry.name;
      const entryFullPath = path.join(fullPath, entry.name);

      if (entry.isDirectory()) {
        // Recursively add subdirectory
        const subFolder = zipFolder.folder(entry.name);
        if (subFolder) {
          await this.addDirectoryToZip(
            subFolder,
            basePath,
            entryRelativePath,
            excludes,
            manifestFiles,
            onProgress
          );
        }
      } else {
        // Add file
        const content = await fs.readFile(entryFullPath);
        zipFolder.file(entry.name, content);
        
        manifestFiles.push({
          path: entryRelativePath,
          size: content.length
        });
        
        onProgress(content.length, 1);
      }
    }
  }

  /**
   * Check if a file/directory should be excluded
   */
  private isExcluded(name: string, excludes: string[]): boolean {
    for (const pattern of excludes) {
      if (pattern.startsWith('*')) {
        // Wildcard pattern
        const suffix = pattern.slice(1);
        if (name.endsWith(suffix)) return true;
      } else {
        // Exact match
        if (name === pattern) return true;
      }
    }
    return false;
  }

  /**
   * Generate README content
   */
  private async generateReadme(options: ZipExportOptions): Promise<string> {
    return `# ${options.projectName}

Generated by **AI Enterprise Architect**

## Quick Start

### 1. Extract this ZIP file
\`\`\`bash
unzip ${options.projectName}.zip
cd ${options.projectName}
\`\`\`

### 2. Install Dependencies
\`\`\`bash
npm install
\`\`\`

### 3. Setup Database
\`\`\`bash
npx prisma generate
npx prisma db push
\`\`\`

### 4. Run Development Server
\`\`\`bash
npm run dev
\`\`\`

### 5. Open in Browser
Navigate to [http://localhost:3000](http://localhost:3000)

## Project Structure

\`\`\`
src/
├── app/              # Next.js App Router pages
├── components/       # React components
│   └── ui/          # UI components (shadcn/ui)
├── hooks/           # Custom React hooks
├── lib/             # Utilities and Prisma client
└── types/           # TypeScript type definitions
prisma/
└── schema.prisma    # Database schema
\`\`\`

## Available Scripts

| Command | Description |
|---------|-------------|
| \`npm run dev\` | Start development server |
| \`npm run build\` | Build for production |
| \`npm run start\` | Start production server |
| \`npm run db:push\` | Push schema to database |
| \`npm run db:studio\` | Open Prisma Studio |

## Environment Variables

Copy \`.env.example\` to \`.env\` and configure:

\`\`\`bash
cp .env.example .env
\`\`\`

## Support

Generated by AI Enterprise Architect
`;
  }

  /**
   * Generate .env.example content
   */
  private async generateEnvExample(): Promise<string> {
    return `# Database Configuration
DATABASE_URL="file:./dev.db"

# For MySQL:
# DATABASE_URL="mysql://user:password@localhost:3306/database"

# For PostgreSQL:
# DATABASE_URL="postgresql://user:password@localhost:5432/database"

# Application Settings
# Add your environment variables here
`;
  }

  /**
   * Generate setup instructions
   */
  private generateInstructions(options: ZipExportOptions): string {
    return `# Setup Instructions

## ${options.projectName}

This project was generated by AI Enterprise Architect on ${new Date().toISOString()}.

## Step-by-Step Setup

### Prerequisites
- Node.js 18+ (LTS recommended)
- npm or yarn or pnpm

### Installation Steps

1. **Extract the ZIP file**
   \`\`\`bash
   unzip ${options.projectName}.zip
   cd ${options.projectName}
   \`\`\`

2. **Install dependencies**
   \`\`\`bash
   npm install
   \`\`\`
   
   This will install all required packages including:
   - Next.js 15
   - React 19
   - Prisma 6
   - Tailwind CSS
   - shadcn/ui components

3. **Setup database**
   \`\`\`bash
   # Generate Prisma client
   npx prisma generate
   
   # Create database and push schema
   npx prisma db push
   \`\`\`

4. **Configure environment** (optional)
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your settings
   \`\`\`

5. **Start development server**
   \`\`\`bash
   npm run dev
   \`\`\`

6. **Open in browser**
   Navigate to http://localhost:3000

## Troubleshooting

### Port already in use
\`\`\`bash
# Use a different port
PORT=3001 npm run dev
\`\`\`

### Database issues
\`\`\`bash
# Reset database
npx prisma migrate reset

# View database in Prisma Studio
npx prisma studio
\`\`\`

### Build errors
\`\`\`bash
# Clear Next.js cache
rm -rf .next
npm run build
\`\`\`

## Next Steps

- Customize the UI components in \`src/components/\`
- Add more pages in \`src/app/\`
- Extend the API routes in \`src/app/api/\`
- Add validation schemas in \`src/lib/validations/\`

---
Generated by AI Enterprise Architect v${this.version}
`;
  }

  /**
   * Create empty manifest for error cases
   */
  private createEmptyManifest(projectName: string): ZipManifest {
    return {
      projectName,
      exportedAt: new Date(),
      files: [],
      totalSize: 0,
      version: this.version
    };
  }
}

// Export singleton
export const zipBuilder = new ZipBuilder();
