import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Building2 } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="container mx-auto py-10">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-bold mb-4">Demo Application</h1>
        <p className="text-muted-foreground">Generated by AI Enterprise Architect</p>
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-4xl mx-auto">
        <Card className="hover:border-primary/50 transition-colors">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Building2 className="w-5 h-5 text-primary" />
              Organizations
            </CardTitle>
            <CardDescription>Manage organization records</CardDescription>
          </CardHeader>
          <CardContent>
            <Link href="/organizations">
              <Button className="w-full">View Organizations</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}