'use client'

/**
 * Generation Studio
 * Code generation interface with preview and export
 * 
 * TASK-4.4: Missing UI Screens
 * Part of Phase 4: Features & User Experience
 */

import React, { useState, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'
import {
  Code2,
  FileCode,
  Database,
  FileJson,
  FileText,
  Download,
  Copy,
  Check,
  Play,
  Settings,
  Sparkles,
  File,
  Folder,
  Loader2,
  AlertCircle,
  CheckCircle2
} from 'lucide-react'

// Types
interface GeneratedFile {
  id: string
  name: string
  path: string
  type: 'prisma' | 'typescript' | 'json' | 'markdown' | 'sql' | 'yaml'
  content: string
  size: number
  valid: boolean
  errors: string[]
  warnings: string[]
}

interface GenerationConfig {
  target: 'prisma' | 'nextjs' | 'react' | 'nestjs' | 'express'
  includeValidation: boolean
  includeTests: boolean
  includeDocs: boolean
  formatCode: boolean
  tableNameCase: 'camel' | 'pascal' | 'snake'
  columnNameCase: 'camel' | 'snake'
}

// Mock generated files
const mockFiles: GeneratedFile[] = [
  {
    id: '1',
    name: 'schema.prisma',
    path: '/prisma/schema.prisma',
    type: 'prisma',
    content: `// Generated by AI Enterprise Architect
// Source: 45 tables parsed from SQL DDL

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Patient {
  id          String   @id @default(cuid())
  mrn         String   @unique
  firstName   String   @map("first_name")
  lastName    String   @map("last_name")
  dateOfBirth DateTime @map("date_of_birth")
  gender      String
  phone       String?
  email       String?
  isActive    Boolean  @default(true) @map("is_active")
  createdAt   DateTime @default(now()) @map("created_at")
  updatedAt   DateTime @updatedAt @map("updated_at")

  visits      Visit[]
  orders      Order[]
  admissions  Admission[]

  @@map("Patients")
}

model Visit {
  id          String   @id @default(cuid())
  patientId   String   @map("patient_id")
  doctorId    String?  @map("doctor_id")
  visitDate   DateTime @map("visit_date")
  status      String   @default("scheduled")
  notes       String?
  createdAt   DateTime @default(now()) @map("created_at")

  patient     Patient  @relation(fields: [patientId], references: [id])
  doctor      Doctor?  @relation(fields: [doctorId], references: [id])

  @@map("Visits")
}`,
    size: 2048,
    valid: true,
    errors: [],
    warnings: ['Consider adding index on patientId']
  },
  {
    id: '2',
    name: 'patient.service.ts',
    path: '/src/services/patient.service.ts',
    type: 'typescript',
    content: `import { PrismaClient, Patient } from '@prisma/client';

const prisma = new PrismaClient();

export class PatientService {
  async findAll(options?: {
    skip?: number;
    take?: number;
    search?: string;
  }): Promise<Patient[]> {
    return prisma.patient.findMany({
      where: options?.search ? {
        OR: [
          { firstName: { contains: options.search } },
          { lastName: { contains: options.search } },
          { mrn: { contains: options.search } }
        ]
      } : undefined,
      skip: options?.skip,
      take: options?.take,
      orderBy: { createdAt: 'desc' }
    });
  }

  async findById(id: string): Promise<Patient | null> {
    return prisma.patient.findUnique({
      where: { id },
      include: {
        visits: { take: 10, orderBy: { visitDate: 'desc' } },
        orders: true
      }
    });
  }

  async create(data: Omit<Patient, 'id' | 'createdAt' | 'updatedAt'>): Promise<Patient> {
    return prisma.patient.create({ data });
  }

  async update(id: string, data: Partial<Patient>): Promise<Patient> {
    return prisma.patient.update({
      where: { id },
      data
    });
  }

  async delete(id: string): Promise<void> {
    await prisma.patient.delete({ where: { id } });
  }
}`,
    size: 1536,
    valid: true,
    errors: [],
    warnings: []
  },
  {
    id: '3',
    name: 'openapi.json',
    path: '/api/openapi.json',
    type: 'json',
    content: JSON.stringify({
      openapi: '3.0.0',
      info: { title: 'HIS API', version: '1.0.0' },
      paths: {
        '/patients': {
          get: {
            summary: 'List all patients',
            parameters: [
              { name: 'search', in: 'query', schema: { type: 'string' } },
              { name: 'skip', in: 'query', schema: { type: 'integer' } },
              { name: 'take', in: 'query', schema: { type: 'integer' } }
            ],
            responses: { '200': { description: 'Success' } }
          }
        }
      }
    }, null, 2),
    size: 1024,
    valid: true,
    errors: [],
    warnings: ['Consider adding security schemes']
  }
]

// File type icons
const FILE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  prisma: Database,
  typescript: Code2,
  json: FileJson,
  markdown: FileText,
  sql: Database,
  yaml: FileCode
}

export function GenerationStudio() {
  const [files, setFiles] = useState<GeneratedFile[]>(mockFiles)
  const [selectedFile, setSelectedFile] = useState<GeneratedFile | null>(mockFiles[0])
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState<string | null>(null)
  const [config, setConfig] = useState<GenerationConfig>({
    target: 'prisma',
    includeValidation: true,
    includeTests: true,
    includeDocs: false,
    formatCode: true,
    tableNameCase: 'pascal',
    columnNameCase: 'camel'
  })

  // Handle generate
  const handleGenerate = useCallback(async () => {
    setIsGenerating(true)
    // Simulate generation
    await new Promise(resolve => setTimeout(resolve, 2000))
    setIsGenerating(false)
  }, [])

  // Handle copy
  const handleCopy = useCallback(async (content: string, fileId: string) => {
    await navigator.clipboard.writeText(content)
    setCopied(fileId)
    setTimeout(() => setCopied(null), 2000)
  }, [])

  // Handle download
  const handleDownload = useCallback((file: GeneratedFile) => {
    const blob = new Blob([file.content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = file.name
    a.click()
    URL.revokeObjectURL(url)
  }, [])

  // Handle download all
  const handleDownloadAll = useCallback(() => {
    // Create a simple export of all files
    const content = files.map(f => `// ${f.path}\n${f.content}`).join('\n\n// ---\n\n')
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'generated-code.txt'
    a.click()
    URL.revokeObjectURL(url)
  }, [files])

  // Get file icon
  const FileIcon = selectedFile ? FILE_ICONS[selectedFile.type] : File

  return (
    <div className="flex h-[calc(100vh-200px)] gap-4">
      {/* File Explorer */}
      <div className="w-72 border border-slate-700 rounded-lg bg-slate-800/50 flex flex-col">
        <div className="p-3 border-b border-slate-700">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-slate-200">Generated Files</h3>
            <Badge variant="secondary" className="text-xs">
              {files.length} files
            </Badge>
          </div>
        </div>

        <ScrollArea className="flex-1">
          <div className="p-2 space-y-1">
            {files.map(file => {
              const Icon = FILE_ICONS[file.type] || File
              const isSelected = selectedFile?.id === file.id

              return (
                <button
                  key={file.id}
                  onClick={() => setSelectedFile(file)}
                  className={`w-full flex items-center gap-2 px-3 py-2 rounded-md text-left transition-colors ${
                    isSelected
                      ? 'bg-purple-500/20 text-purple-300'
                      : 'hover:bg-slate-700/50 text-slate-300'
                  }`}
                >
                  <Icon className="w-4 h-4 shrink-0" />
                  <div className="flex-1 min-w-0">
                    <div className="text-sm truncate">{file.name}</div>
                    <div className="text-xs text-slate-500 truncate">{file.path}</div>
                  </div>
                  {file.valid ? (
                    <CheckCircle2 className="w-4 h-4 text-green-500 shrink-0" />
                  ) : (
                    <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
                  )}
                </button>
              )
            })}
          </div>
        </ScrollArea>

        <div className="p-3 border-t border-slate-700">
          <Button
            className="w-full"
            onClick={handleDownloadAll}
            disabled={files.length === 0}
          >
            <Download className="w-4 h-4 mr-2" />
            Download All
          </Button>
        </div>
      </div>

      {/* Code Editor */}
      <div className="flex-1 flex flex-col">
        {selectedFile ? (
          <>
            {/* Editor Header */}
            <div className="flex items-center justify-between px-4 py-2 border-b border-slate-700 bg-slate-800/30 rounded-t-lg">
              <div className="flex items-center gap-3">
                <FileIcon className="w-4 h-4 text-purple-400" />
                <span className="text-sm text-slate-200">{selectedFile.path}</span>
                <Badge variant="outline" className="text-xs">
                  {(selectedFile.size / 1024).toFixed(1)} KB
                </Badge>
              </div>

              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleCopy(selectedFile.content, selectedFile.id)}
                >
                  {copied === selectedFile.id ? (
                    <Check className="w-4 h-4 text-green-500" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleDownload(selectedFile)}
                >
                  <Download className="w-4 h-4" />
                </Button>
              </div>
            </div>

            {/* Editor Content */}
            <div className="flex-1 relative">
              <ScrollArea className="h-full">
                <pre className="p-4 text-sm font-mono text-slate-300 whitespace-pre-wrap">
                  {selectedFile.content}
                </pre>
              </ScrollArea>
            </div>

            {/* Validation Results */}
            {(selectedFile.errors.length > 0 || selectedFile.warnings.length > 0) && (
              <div className="border-t border-slate-700 bg-slate-800/30 p-3">
                {selectedFile.errors.map((error, idx) => (
                  <div key={idx} className="text-sm text-red-400 flex items-center gap-2 mb-1">
                    <AlertCircle className="w-4 h-4" />
                    {error}
                  </div>
                ))}
                {selectedFile.warnings.map((warning, idx) => (
                  <div key={idx} className="text-sm text-yellow-400 flex items-center gap-2 mb-1">
                    <AlertCircle className="w-4 h-4" />
                    {warning}
                  </div>
                ))}
              </div>
            )}
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-slate-400">
            <div className="text-center">
              <File className="w-12 h-12 mx-auto mb-4 opacity-50" />
              <p>Select a file to preview</p>
            </div>
          </div>
        )}
      </div>

      {/* Settings Panel */}
      <div className="w-72 border border-slate-700 rounded-lg bg-slate-800/50 flex flex-col">
        <div className="p-3 border-b border-slate-700">
          <h3 className="text-sm font-medium text-slate-200 flex items-center gap-2">
            <Settings className="w-4 h-4" />
            Generation Settings
          </h3>
        </div>

        <div className="flex-1 p-3 space-y-4">
          <div>
            <label className="text-xs text-slate-400 mb-1 block">Target Framework</label>
            <Select
              value={config.target}
              onValueChange={(value) => setConfig(prev => ({ ...prev, target: value as any }))}
            >
              <SelectTrigger className="bg-slate-700/50 border-slate-600">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="prisma">Prisma Schema</SelectItem>
                <SelectItem value="nextjs">Next.js App Router</SelectItem>
                <SelectItem value="react">React Components</SelectItem>
                <SelectItem value="nestjs">NestJS Modules</SelectItem>
                <SelectItem value="express">Express.js Routes</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">Table Name Case</label>
            <Select
              value={config.tableNameCase}
              onValueChange={(value) => setConfig(prev => ({ ...prev, tableNameCase: value as any }))}
            >
              <SelectTrigger className="bg-slate-700/50 border-slate-600">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="pascal">PascalCase</SelectItem>
                <SelectItem value="camel">camelCase</SelectItem>
                <SelectItem value="snake">snake_case</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">Column Name Case</label>
            <Select
              value={config.columnNameCase}
              onValueChange={(value) => setConfig(prev => ({ ...prev, columnNameCase: value as any }))}
            >
              <SelectTrigger className="bg-slate-700/50 border-slate-600">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="camel">camelCase</SelectItem>
                <SelectItem value="snake">snake_case</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label className="flex items-center gap-2 text-sm text-slate-300">
              <input
                type="checkbox"
                checked={config.includeValidation}
                onChange={(e) => setConfig(prev => ({ ...prev, includeValidation: e.target.checked }))}
                className="rounded border-slate-600"
              />
              Include Validation
            </label>

            <label className="flex items-center gap-2 text-sm text-slate-300">
              <input
                type="checkbox"
                checked={config.includeTests}
                onChange={(e) => setConfig(prev => ({ ...prev, includeTests: e.target.checked }))}
                className="rounded border-slate-600"
              />
              Include Tests
            </label>

            <label className="flex items-center gap-2 text-sm text-slate-300">
              <input
                type="checkbox"
                checked={config.includeDocs}
                onChange={(e) => setConfig(prev => ({ ...prev, includeDocs: e.target.checked }))}
                className="rounded border-slate-600"
              />
              Include Documentation
            </label>

            <label className="flex items-center gap-2 text-sm text-slate-300">
              <input
                type="checkbox"
                checked={config.formatCode}
                onChange={(e) => setConfig(prev => ({ ...prev, formatCode: e.target.checked }))}
                className="rounded border-slate-600"
              />
              Format Code
            </label>
          </div>
        </div>

        <div className="p-3 border-t border-slate-700">
          <Button
            className="w-full"
            onClick={handleGenerate}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Code
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  )
}

export default GenerationStudio
