'use client'

import { useState, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useTheme } from '@/hooks/useTheme'
import { Key, Loader2, AlertTriangle, CheckCircle, ArrowRight, Database, FileCode, Link2, Upload, FileText, Sparkles, ChevronDown, ChevronUp, X, Copy, Check } from 'lucide-react'

export default function FKResolutionPage() {
  const params = useParams()
  const router = useRouter()
  const { colors } = useTheme()
  const projectId = params.id as string

  const [analysis, setAnalysis] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [expandedTable, setExpandedTable] = useState<string | null>(null)
  const [generatedSQL, setGeneratedSQL] = useState<Record<string, string>>({})
  const [copiedTable, setCopiedTable] = useState<string | null>(null)
  const [generatingTable, setGeneratingTable] = useState<string | null>(null)

  useEffect(() => {
    fetchAnalysis()
  }, [projectId])

  const fetchAnalysis = async () => {
    try {
      const response = await fetch(`/api/project-status?projectId=${projectId}`)
      if (response.ok) {
        const data = await response.json()
        setAnalysis(data.fkAnalysis || {})
      }
    } finally {
      setLoading(false)
    }
  }

  const generateSQLSchema = async (tableName: string) => {
    setGeneratingTable(tableName)
    try {
      // Find FK fields that reference this table
      const response = await fetch(`/api/project-status?projectId=${projectId}`)
      const data = await response.json()
      
      // Get columns from CSHTML views that have FK to this table
      const fkColumns: any[] = []
      for (const view of data.cshtmlViews || []) {
        for (const field of view.fields || []) {
          if (field.isFK && field.fkTable === tableName) {
            fkColumns.push({
              name: field.name,
              sqlType: field.sqlType || 'INT'
            })
          }
        }
      }

      // Generate SQL based on table name patterns
      const sql = generateTableSQL(tableName, fkColumns)
      setGeneratedSQL(prev => ({ ...prev, [tableName]: sql }))
    } catch (error) {
      console.error('Error generating SQL:', error)
    } finally {
      setGeneratingTable(null)
    }
  }

  const generateTableSQL = (tableName: string, fkColumns: any[]): string => {
    const commonColumns = [
      { name: 'Id', type: 'INT IDENTITY(1,1) PRIMARY KEY' },
      { name: 'Name', type: 'NVARCHAR(200) NOT NULL' },
      { name: 'Description', type: 'NVARCHAR(500) NULL' },
      { name: 'IsActive', type: 'BIT DEFAULT 1' },
      { name: 'CreatedDate', type: 'DATETIME2 DEFAULT GETDATE()' },
      { name: 'ModifiedDate', type: 'DATETIME2 NULL' }
    ]

    // Customize based on table name
    let customColumns: any[] = []
    
    if (tableName === 'Country') {
      customColumns = [
        { name: 'CountryCode', type: 'VARCHAR(10) UNIQUE NOT NULL' },
        { name: 'ISOCode', type: 'VARCHAR(3) UNIQUE' },
        { name: 'PhoneCode', type: 'VARCHAR(10)' },
        { name: 'Currency', type: 'VARCHAR(10)' },
        { name: 'FlagUrl', type: 'VARCHAR(500)' }
      ]
    } else if (tableName === 'Province' || tableName === 'State') {
      customColumns = [
        { name: 'Code', type: 'VARCHAR(20) UNIQUE' },
        { name: 'CountryId', type: 'INT NOT NULL' },
        { name: 'CountryId_FK', type: 'FOREIGN KEY (CountryId) REFERENCES Country(Id)' }
      ]
    } else if (tableName === 'City') {
      customColumns = [
        { name: 'Code', type: 'VARCHAR(20)' },
        { name: 'ProvinceId', type: 'INT NOT NULL' },
        { name: 'ProvinceId_FK', type: 'FOREIGN KEY (ProvinceId) REFERENCES Province(Id)' },
        { name: 'PostalCode', type: 'VARCHAR(20)' }
      ]
    } else if (tableName === 'OrganizationType' || tableName === 'Branche') {
      customColumns = [
        { name: 'Code', type: 'VARCHAR(20) UNIQUE NOT NULL' },
        { name: 'SortOrder', type: 'INT DEFAULT 0' },
        { name: 'ParentId', type: 'INT NULL' },
        { name: 'ParentId_FK', type: 'FOREIGN KEY (ParentId) REFERENCES ' + tableName + '(Id)' }
      ]
    }

    const allColumns = [...commonColumns, ...customColumns.filter(c => !c.name.endsWith('_FK'))]
    const fkConstraints = customColumns.filter(c => c.name.endsWith('_FK'))

    let sql = `-- =============================================
-- Table: ${tableName}
-- Generated by Schema Architect AI
-- =============================================

CREATE TABLE [dbo].[${tableName}] (
${allColumns.map(c => `    [${c.name}] ${c.type},`).join('\n')}
`

    if (fkConstraints.length > 0) {
      sql += `\n    -- Foreign Keys\n`
      sql += fkConstraints.map(c => `    CONSTRAINT [FK_${tableName}_${c.name.replace('_FK', '')}] ${c.type},`).join('\n')
    }

    // Remove trailing comma and close
    sql = sql.slice(0, -1) + '\n);\n'

    // Add indexes
    sql += `\n-- Create indexes for better query performance
CREATE INDEX [IX_${tableName}_Name] ON [dbo].[${tableName}]([Name]);
CREATE INDEX [IX_${tableName}_IsActive] ON [dbo].[${tableName}]([IsActive]);
`

    // Add sample data
    sql += `\n-- Sample data (uncomment to use)
/*
INSERT INTO [dbo].[${tableName}] (Name, Description, IsActive)
VALUES 
    ('Sample ${tableName} 1', 'Description 1', 1),
    ('Sample ${tableName} 2', 'Description 2', 1),
    ('Sample ${tableName} 3', 'Description 3', 1);
*/
`
    return sql
  }

  const copyToClipboard = async (tableName: string, sql: string) => {
    try {
      await navigator.clipboard.writeText(sql)
      setCopiedTable(tableName)
      setTimeout(() => setCopiedTable(null), 2000)
    } catch (error) {
      console.error('Failed to copy:', error)
    }
  }

  const downloadSQL = (tableName: string, sql: string) => {
    const blob = new Blob([sql], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${tableName}.sql`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-6 h-6 animate-spin" style={{ color: colors.primary }} />
      </div>
    )
  }

  const totalFKs = analysis?.totalFKs || 0
  const resolvedFKs = analysis?.resolvedFKs || 0
  const missingTables = analysis?.missingTables || []
  const summary = analysis?.summary || {}

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-4 gap-4">
        <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <div className="flex items-center gap-2">
            <Key className="w-5 h-5" style={{ color: colors.primary }} />
            <span className="text-sm" style={{ color: colors.textMuted }}>Total FKs</span>
          </div>
          <p className="text-2xl font-bold" style={{ color: colors.text }}>{totalFKs}</p>
        </div>
        
        <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <div className="flex items-center gap-2">
            <CheckCircle className="w-5 h-5" style={{ color: '#10b981' }} />
            <span className="text-sm" style={{ color: colors.textMuted }}>Resolved</span>
          </div>
          <p className="text-2xl font-bold" style={{ color: '#10b981' }}>{resolvedFKs}</p>
        </div>
        
        <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-5 h-5" style={{ color: '#f59e0b' }} />
            <span className="text-sm" style={{ color: colors.textMuted }}>Missing Tables</span>
          </div>
          <p className="text-2xl font-bold" style={{ color: '#f59e0b' }}>{missingTables.length}</p>
        </div>
        
        <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5" style={{ color: colors.primary }} />
            <span className="text-sm" style={{ color: colors.textMuted }}>Known Tables</span>
          </div>
          <p className="text-2xl font-bold" style={{ color: colors.text }}>{summary?.knownTables || 0}</p>
        </div>
      </div>

      {/* Source Breakdown */}
      {summary && (
        <div className="grid grid-cols-2 gap-4">
          <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
            <div className="flex items-center gap-2">
              <FileCode className="w-5 h-5" style={{ color: '#6366f1' }} />
              <span className="text-sm" style={{ color: colors.textMuted }}>FKs from SQL DDL</span>
            </div>
            <p className="text-xl font-bold" style={{ color: colors.text }}>{summary.fromSQL || 0}</p>
          </div>
          
          <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
            <div className="flex items-center gap-2">
              <Link2 className="w-5 h-5" style={{ color: '#8b5cf6' }} />
              <span className="text-sm" style={{ color: colors.textMuted }}>FKs from CSHTML</span>
            </div>
            <p className="text-xl font-bold" style={{ color: colors.text }}>{summary.fromCSHTML || 0}</p>
          </div>
        </div>
      )}

      {/* Resolution Progress */}
      <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
        <h3 className="text-lg font-semibold mb-4" style={{ color: colors.text }}>Resolution Progress</h3>
        <div className="space-y-3">
          <div className="flex justify-between items-center">
            <span style={{ color: colors.textMuted }}>FK Resolution Rate</span>
            <span className="font-medium" style={{ color: colors.text }}>
              {totalFKs > 0 ? Math.round((resolvedFKs / totalFKs) * 100) : 0}%
            </span>
          </div>
          <div className="w-full bg-gray-200 rounded-full h-3">
            <div 
              className="h-3 rounded-full transition-all"
              style={{ 
                width: `${totalFKs > 0 ? (resolvedFKs / totalFKs) * 100 : 0}%`,
                backgroundColor: resolvedFKs === totalFKs ? '#10b981' : '#f59e0b'
              }}
            />
          </div>
          <p className="text-sm" style={{ color: colors.textMuted }}>
            {resolvedFKs} of {totalFKs} FKs resolved ({totalFKs - resolvedFKs} pending)
          </p>
        </div>
      </div>

      {/* Missing Tables List with Actions */}
      {missingTables.length > 0 ? (
        <div className="p-4 rounded-lg border" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <h3 className="text-lg font-semibold mb-4 flex items-center gap-2" style={{ color: colors.text }}>
            <AlertTriangle className="w-5 h-5 text-amber-500" />
            Missing Tables ({missingTables.length})
          </h3>
          <div className="space-y-3">
            {missingTables.map((table: string, idx: number) => (
              <div key={idx} className="border rounded-lg overflow-hidden" style={{ borderColor: colors.border }}>
                {/* Table Header */}
                <div 
                  className="flex items-center justify-between p-3 cursor-pointer hover:opacity-90"
                  style={{ backgroundColor: colors.bg }}
                  onClick={() => setExpandedTable(expandedTable === table ? null : table)}
                >
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded flex items-center justify-center" style={{ backgroundColor: '#fef3c7' }}>
                      <Database className="w-4 h-4 text-amber-600" />
                    </div>
                    <div>
                      <span className="font-medium" style={{ color: colors.text }}>{table}</span>
                      <p className="text-xs" style={{ color: colors.textMuted }}>
                        Referenced by {(analysis?.summary?.fromCSHTML || 0)} FK(s)
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {generatedSQL[table] && (
                      <span className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-600">SQL Generated</span>
                    )}
                    {expandedTable === table ? (
                      <ChevronUp className="w-5 h-5" style={{ color: colors.textMuted }} />
                    ) : (
                      <ChevronDown className="w-5 h-5" style={{ color: colors.textMuted }} />
                    )}
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="p-3 border-t flex flex-wrap gap-2" style={{ borderColor: colors.border }}>
                  <button
                    className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm"
                    style={{ backgroundColor: colors.primary, color: '#fff' }}
                    onClick={() => router.push(`/project/${projectId}/upload`)}
                  >
                    <Upload className="w-4 h-4" />
                    Upload SQL File
                  </button>
                  
                  <button
                    className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm border"
                    style={{ borderColor: colors.border, color: colors.text }}
                    onClick={() => {
                      if (generatedSQL[table]) {
                        downloadSQL(table, generatedSQL[table])
                      }
                    }}
                    disabled={!generatedSQL[table]}
                  >
                    <FileText className="w-4 h-4" />
                    View Schema
                  </button>
                  
                  <button
                    className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm"
                    style={{ 
                      backgroundColor: generatingTable === table ? colors.border : '#8b5cf6', 
                      color: '#fff' 
                    }}
                    onClick={() => generateSQLSchema(table)}
                    disabled={generatingTable === table}
                  >
                    {generatingTable === table ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Sparkles className="w-4 h-4" />
                    )}
                    AI Generate
                  </button>
                </div>

                {/* Generated SQL Display */}
                {expandedTable === table && generatedSQL[table] && (
                  <div className="p-3 border-t" style={{ borderColor: colors.border }}>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium" style={{ color: colors.text }}>Generated SQL Schema</span>
                      <div className="flex gap-2">
                        <button
                          className="flex items-center gap-1 px-2 py-1 rounded text-xs"
                          style={{ backgroundColor: colors.bg, color: colors.text }}
                          onClick={() => copyToClipboard(table, generatedSQL[table])}
                        >
                          {copiedTable === table ? (
                            <>
                              <Check className="w-3 h-3 text-green-500" />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy className="w-3 h-3" />
                              Copy
                            </>
                          )}
                        </button>
                        <button
                          className="flex items-center gap-1 px-2 py-1 rounded text-xs"
                          style={{ backgroundColor: colors.primary, color: '#fff' }}
                          onClick={() => downloadSQL(table, generatedSQL[table])}
                        >
                          <FileText className="w-3 h-3" />
                          Download .sql
                        </button>
                      </div>
                    </div>
                    <pre 
                      className="p-3 rounded-lg text-xs overflow-auto max-h-64"
                      style={{ backgroundColor: '#1e1e1e', color: '#d4d4d4' }}
                    >
                      {generatedSQL[table]}
                    </pre>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="p-6 rounded-lg border text-center" style={{ borderColor: colors.border, backgroundColor: colors.cardBg }}>
          <CheckCircle className="w-12 h-12 mx-auto mb-4" style={{ color: '#10b981' }} />
          <p className="text-lg font-medium" style={{ color: colors.text }}>All foreign keys resolved!</p>
          {summary && (
            <p className="text-sm mt-2" style={{ color: colors.textMuted }}>
              From {summary.discoveredTables} discovered tables and {summary.fromSQL} SQL FK definitions
            </p>
          )}
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex gap-4">
        <button
          className="flex items-center gap-2 px-4 py-2 rounded-lg"
          style={{ backgroundColor: colors.primary, color: '#fff' }}
          onClick={() => router.push(`/project/${projectId}/upload`)}
        >
          <Upload className="w-4 h-4" />
          Upload SQL Files
        </button>
        
        <button
          className="flex items-center gap-2 px-4 py-2 rounded-lg border"
          style={{ borderColor: colors.border, color: colors.text }}
          onClick={() => router.push(`/project/${projectId}/tables`)}
        >
          <Database className="w-4 h-4" />
          View All Tables
        </button>
      </div>
    </div>
  )
}
